# Generated by Django 5.2.4 on 2025-09-14 02:06

import django.db.models.deletion
import myApplicationManager.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsToApply',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('jobID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('companyName', models.TextField(default='')),
                ('position', models.TextField(default='')),
                ('salary', models.TextField(default='')),
                ('jobDetails', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('profileID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=30)),
                ('phoneNumber', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=50)),
                ('province', models.CharField(default='', max_length=50)),
                ('postalCode', models.CharField(default='', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('resumeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='')),
                ('uploadDate', models.DateTimeField(default=myApplicationManager.models.get_mst_time)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApplicationManager.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('APPLIED', 'applied'), ('INTERVIEW', 'interview')], default='APPLIED', max_length=20)),
                ('jobID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApplicationManager.jobstoapply')),
                ('profileID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApplicationManager.profile')),
                ('resumeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApplicationManager.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('resumeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='myApplicationManager.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('school_name', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('resumeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='myApplicationManager.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=50)),
                ('resumeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myApplicationManager.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
