# Generated by Django 5.2.4 on 2025-09-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "accepted"),
                            ("REJECTED", "rejected"),
                            ("APPLIED", "applied"),
                            ("INTERVIEW", "interview"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("companyName", models.TextField(default="")),
                ("postion", models.TextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
