# Generated by Django 5.2.4 on 2025-09-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApplicationManager', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.TextField(default='', max_length=30),
        ),
    ]
