# Generated by Django 5.2.4 on 2025-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApplicationManager', '0003_remove_jobapplication_jobid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
