# Generated by Django 5.2.4 on 2025-09-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApplicationManager', '0003_remove_profile_address_profile_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='userID',
            new_name='profileID',
        ),
    ]
