# Generated by Django 5.2.4 on 2025-09-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApplicationManager', '0004_rename_userid_resume_profileid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='profileID',
            new_name='userID',
        ),
    ]
