# Generated by Django 5.2.4 on 2025-09-14 07:27

import myApplicationManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApplicationManager', '0005_rename_profileid_resume_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstoapply',
            name='appliedDate',
            field=models.DateTimeField(default=myApplicationManager.models.get_mst_time),
        ),
    ]
