# Generated by Django 5.2.4 on 2025-09-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApplicationManager', '0004_alter_jobapplication_job_url'),
        ('myApplicationManager', '0006_jobstoapply_applieddate'),
    ]

    operations = [
    ]
