# Generated by Django 5.2.4 on 2025-09-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApplicationManager', '0007_merge_20250914_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='profileID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myApplicationManager.profile'),
            preserve_default=False,
        ),
    ]
